name: Build


on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
#       checkout
      - uses: actions/checkout@v1
      - name: set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 1.18

#       build project and run all tests & checks
      - name: Maven Verify
        run: mvn -B clean verify
